[package]
name = "numer0n_contract"
type = "contract"
authors = ["abstract-crypto"]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.7', directory = 'yarn-project/aztec-nr/aztec' }
authwit = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.7', directory = 'yarn-project/aztec-nr/authwit' }
value_note = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.7', directory = 'yarn-project/aztec-nr/value-note' }
protocol_types = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.16.7', directory = 'yarn-project/noir-protocol-circuits/src/crates/types' }