[package]
name = "numer0n_contract"
type = "contract"
authors = ["porco"]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.67.0', directory = 'noir-projects/aztec-nr/aztec' }
authwit = { git = 'https://github.com/AztecProtocol/aztec-packages/', tag = 'aztec-packages-v0.67.0', directory = 'noir-projects/aztec-nr/authwit' }