/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
	type AbiType,
	AztecAddress,
	type AztecAddressLike,
	CompleteAddress,
	Contract,
	type ContractArtifact,
	ContractBase,
	ContractFunctionInteraction,
	type ContractInstanceWithAddress,
	type ContractMethod,
	type ContractStorageLayout,
	type ContractNotes,
	decodeFromAbi,
	DeployMethod,
	EthAddress,
	type EthAddressLike,
	EventSelector,
	type FieldLike,
	Fr,
	type FunctionSelectorLike,
	L1EventPayload,
	loadContractArtifact,
	type NoirCompiledContract,
	NoteSelector,
	Point,
	type PublicKey,
	PublicKeys,
	type UnencryptedL2Log,
	type Wallet,
	type WrappedFieldLike,
} from "@aztec/aztec.js";
import Numer0nContractArtifactJson from "./numer0n_contract-Numer0n.json" assert { type: "json" };
export const Numer0nContractArtifact = loadContractArtifact(
	Numer0nContractArtifactJson as NoirCompiledContract
);

/**
 * Type-safe interface for contract Numer0n;
 */
export class Numer0nContract extends ContractBase {
	private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
		super(instance, Numer0nContractArtifact, wallet);
	}

	/**
	 * Creates a contract instance.
	 * @param address - The deployed contract's address.
	 * @param wallet - The wallet to use when interacting with the contract.
	 * @returns A promise that resolves to a new Contract instance.
	 */
	public static async at(address: AztecAddress, wallet: Wallet) {
		return Contract.at(
			address,
			Numer0nContract.artifact,
			wallet
		) as Promise<Numer0nContract>;
	}

	/**
	 * Creates a tx to deploy a new instance of this contract.
	 */
	public static deploy(
		wallet: Wallet,
		player: AztecAddressLike,
		secret_game_code: FieldLike
	) {
		return new DeployMethod<Numer0nContract>(
			PublicKeys.default(),
			wallet,
			Numer0nContractArtifact,
			Numer0nContract.at,
			Array.from(arguments).slice(1)
		);
	}

	/**
	 * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
	 */
	public static deployWithPublicKeys(
		publicKeys: PublicKeys,
		wallet: Wallet,
		player: AztecAddressLike,
		secret_game_code: FieldLike
	) {
		return new DeployMethod<Numer0nContract>(
			publicKeys,
			wallet,
			Numer0nContractArtifact,
			Numer0nContract.at,
			Array.from(arguments).slice(2)
		);
	}

	/**
	 * Creates a tx to deploy a new instance of this contract using the specified constructor method.
	 */
	public static deployWithOpts<M extends keyof Numer0nContract["methods"]>(
		opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
		...args: Parameters<Numer0nContract["methods"][M]>
	) {
		return new DeployMethod<Numer0nContract>(
			opts.publicKeys ?? PublicKeys.default(),
			opts.wallet,
			Numer0nContractArtifact,
			Numer0nContract.at,
			Array.from(arguments).slice(1),
			opts.method ?? "constructor"
		);
	}

	/**
	 * Returns this contract's artifact.
	 */
	public static get artifact(): ContractArtifact {
		return Numer0nContractArtifact;
	}

	public static get storage(): ContractStorageLayout<
		"secret_game_code_hash" | "players" | "secret_num" | "guesses" | "game"
	> {
		return {
			secret_game_code_hash: {
				slot: new Fr(1n),
			},
			players: {
				slot: new Fr(2n),
			},
			secret_num: {
				slot: new Fr(3n),
			},
			guesses: {
				slot: new Fr(4n),
			},
			game: {
				slot: new Fr(5n),
			},
		} as ContractStorageLayout<
			"secret_game_code_hash" | "players" | "secret_num" | "guesses" | "game"
		>;
	}

	public static get notes(): ContractNotes<"SecretNumberNote"> {
		return {
			SecretNumberNote: {
				id: new NoteSelector(2366349985),
			},
		} as ContractNotes<"SecretNumberNote">;
	}

	/** Type-safe wrappers for the public methods exposed by the contract. */
	public declare methods: {
		/** add_num(player: struct, secret_num: integer) */
		add_num: ((
			player: AztecAddressLike,
			secret_num: bigint | number
		) => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** check_result(guess_num: integer, secret_num: integer) */
		check_result: ((
			guess_num: bigint | number,
			secret_num: bigint | number
		) => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
		compute_note_hash_and_optionally_a_nullifier: ((
			contract_address: AztecAddressLike,
			nonce: FieldLike,
			storage_slot: FieldLike,
			note_type_id: FieldLike,
			compute_nullifier: boolean,
			serialized_note: FieldLike[]
		) => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** constructor(player: struct, secret_game_code: field) */
		constructor: ((
			player: AztecAddressLike,
			secret_game_code: FieldLike
		) => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** evaluate_guess(guessed: struct, guesser: struct, guess_num: integer) */
		evaluate_guess: ((
			guessed: AztecAddressLike,
			guesser: AztecAddressLike,
			guess_num: bigint | number
		) => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** get_game() */
		get_game: (() => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** get_guess(player: struct, round: integer) */
		get_guess: ((
			player: AztecAddressLike,
			round: bigint | number
		) => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** get_guesses(player: struct) */
		get_guesses: ((player: AztecAddressLike) => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** get_is_first() */
		get_is_first: (() => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** get_player(player: struct) */
		get_player: ((player: AztecAddressLike) => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** get_players() */
		get_players: (() => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** get_round() */
		get_round: (() => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** get_secret_num(player: struct) */
		get_secret_num: ((
			player: AztecAddressLike
		) => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** get_winner() */
		get_winner: (() => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** guess_num(player: struct, guess_num: integer) */
		guess_num: ((
			player: AztecAddressLike,
			guess_num: bigint | number
		) => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** is_valid_nums(_num: integer) */
		is_valid_nums: ((_num: bigint | number) => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** join_game(player: struct, secret_game_code: field) */
		join_game: ((
			player: AztecAddressLike,
			secret_game_code: FieldLike
		) => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** public_dispatch(selector: field) */
		public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;

		/** sync_notes() */
		sync_notes: (() => ContractFunctionInteraction) &
			Pick<ContractMethod, "selector">;
	};
}
